language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt510base qt510svg
  - source /opt/qt510/bin/qt510-env.sh 


script:
  - /opt/qt510/bin/qmake PREFIX=/usr
  - make -j$(nproc)
  - # Generate AppImage
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir -p appdir/usr/bin ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ./usr/share/icons/hicolor/48x48/apps/cutepeaks.png .
  - cp ./usr/share/applications/cutepeaks.desktop .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -appimage 
  - curl --upload-file ./cutepeaks-*.AppImage https://transfer.sh/cutepeaks-git.$(git rev-parse --short HEAD)-x86_64.AppImage 
  

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh cutepeaks-*.AppImage*


# For gitter 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/222aecab8c95bc7227a1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# Temporarily disabled so that AppImage generation can be tested
# branches:
#   only:
#    - master