name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: sudo apt-get install qt5-default libqt5svg5-dev
    - name: run qmake
      run: qmake cutepeaks.pro
    - name: make
      run: make
